### ISSUE TITLE
Not work with beta 16

### ISSUE THREAD

**Issue by exshapoval** [FriendsOfFlarum/realtimedate#16]
Problem 1
    - Root composer.json requires fof/realtimedate ^0.3.0 -> satisfiable by fof/realtimedate[0.3.0].
    - fof/realtimedate 0.3.0 requires flarum/core ^0.1.0-beta.16 -> found flarum/core[v0.1.0-beta.16] but it does not match your minimum-stability.

**Comment by dsevillamartin** [comment]
As this is a minimum-stability error, I assume you are not on Flarum betas (judging by your creation of #17 as well).
This extension should be working on Flarum beta 16, but one should not be using the Flarum betas since quite some time.
